### ISSUE TITLE
Love the boilerplate, just wondering...

### ISSUE THREAD

**Issue by ktmn** [xpepermint/isomorphic-react-relay-boilerplate#1]
How does it differ from what is described here:

https://github.com/facebook/relay/issues/36#issuecomment-130402024

Once these hooks get released am I gonna have to make serious changes to my app if it were to be based on this boilerplate?

**Comment by xpepermint** [comment]
Hey. This project is more like a documentation on how to build an app and does not implement any new features. Steps from 0 to 6 are ready and you can use it in production. Currently I work on step 7 - `relay` implementation. Node in my view should not be packed into a huge and unreadable framework. Facebook published some tutorials but the code doesn't look long-term sustainable. My goal is to make this boilerplate as clean and easy as possible. For each feature I create a document under `docs` so a user can build the project from scratch based on that steps.
I have not yet found the best way to implement relay but I'm working on it. The biggest issue is the schema. Relay simplifies things but adds confusion and I must figure out how to make a proper story from it so everyone will understand. Let's wait for some time to find the easy way. 
All good proposals are welcome...
