### ISSUE TITLE
Relay?

### ISSUE THREAD

**Issue by liesislukas** [xpepermint/isomorphic-react-relay-boilerplate#6]
I've looked through your code but can't find usage of Relay. Do you actually use it? Where? Looking for working isomorphic examples with Relay.

**Comment by xpepermint** [comment]
Hey. The `readme` says `Work in progress!`. File `isomorphic-react-relay-boilerplate/docs/X-relay.md` holds my notes. I'm still working on this last part. I hope it will be ready soon.

**Comment by liesislukas** [comment]
Is it possible to make Relay isomorphic or it's too coupled with browser?

**Comment by xpepermint** [comment]
Sure, but people are having issues. I follow Facebook discussions and wait for those issues to be resolved. I also have to figure how to make the code look clean and easy to read (e.g. implement relay in 3 easy steps) - it's kind of confusing/complicated right now. If you have suggestions, or useful links, please post them here. Thanks.

**Comment by jj117** [comment]
Are you still working on this?

**Comment by alexcontanu** [comment]
Are you still working on this?

**Comment by xpepermint** [comment]
I haven't got time to dig into this yet.
